### ISSUE TITLE
Watch Dir

### ISSUE THREAD

**Issue by scottclin** [scottclin/etontables#4]
Not so sure how we could do this better but any road. I think maybe given we have multi threading going on we should change the watch dir conf option to be a slice? Not sure a map is the right way to go. 

Would need to come up with a drop dir func as well as a isTracked(?) func. 

I think this is better then a single string, would need to support on clientside the arg line passing of more dirs. Let me know what you think.

**Comment by voidshard** [comment]
Wait, isn't watched dirs a slice of strings already? 

```
func GetWatchDirs() []string { 
    return conf.watch_dirs 
}
```

[edit]

Drop dir sounds like a good idea .. as well as 'list me the current watched dirs" being accessible from the api

**Comment by scottclin** [comment]
So right, yeah looks I wrote this in a blind moment. 

So yeah drop and add will have to be a thing. I suppose the config is a bas point for the server and then it goes from there?

**Comment by scottclin** [comment]
Done in commit: 9ec56ba
